lip-X.md

I fixed some of the references of Ethereum in the LIP template.
There're still some in the `specification` section that I don't know if we should change.

Small changes on LIP template

---

LSPs/LSP-2-ERC725YJSONSchema.md

While experimenting with erc725.js I realized it never recognized the hashFunction

Adjust length of "hashFunction" string

---

.prettierignore
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-6-KeyManager.md

Fixes errors in LSP2 and LSP6 specs
- Disable Prettier on Markdown files, so to make it easier to track LSP spec changes (otherwise, Prettier apply automatic formatting, white spaces, etc...)
- changed from  ❌  `LSP2IssuedAssets[]` to  ✅  **`LSP3IssuedAssets[]`** +  changed `keccak256` hashes in spec.
- Added `AddressPermissions[]` key in spec.
- Edited Permission keys type from _Singleton_ to _AddressMappingWithGrouping_
- Added requirements for signature in `executeRelayCall` (packed encoded + use EIP712 Ethereum specific signature)
- Made image size smaller for multi channel nonce.

Add extra LSP6 Key, fix Errors on LSP2 and 6 + disable Prettier

---

LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-6-KeyManager.md

@YamenMerhi @frozeman , for the function `getNonce(...)` (in both the **Methods** and **Interface SheetCheat**), should we put the`_channel` parameter as `uint128` instead of `uint256`?
This would align with what is mentioned above the figure in [**Nonces in the KeyManager**](https://github.com/lukso-network/LIPs/blob/master/LSPs/LSP-6-KeyManager.md#nonces-in-the-keymanager)

Order of params for executeRelayCall + Fixed Interface Sheetcheat

---

LSPs/LSP-6-KeyManager.md

- So that they can be used via copy-pasting ✅ 
Permissions values for `AddressPermissions:Permissions:<address>` must be written as `bytes32` long + **zero left-padded**
The current examples show them as `0x0004`.
If these values are used via copy-pasting in code snippets, they will be zero right-padded, and will lead to odd or difficult to debug revert errors from the Key Manager.

LSP6 - write permissions as bytes32 with zero left-padding

---

LSPs/LSP-6-KeyManager.md

The header in LSP6 does not display correctly anymore.
See here: https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md
This PR fixes it.

Fix header issue in LSP6

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Small PR to sync the content of docs.lukso.tech with the current standards, as the word `token` should be used in the LSP7/8 function and not `asset`

docs: switch from `asset` to `token` keyword

---

LSPs/LSP-6-KeyManager.md

Introduction of new permission in LSP6 - Key Manager
- add new permission `ADDPERMISSIONS` + edit description
- edit chart for permission range examples (see below)

LSP6: new permission `ADDPERMISSION`

---

LSPs/LSP-4-DigitalAsset-Metadata.md

LSP4 is now Digital**Asset** (before Digital~Certificate~)
Therefore replace first 4 bytes of keccak256 hash of the word as below:
`SupportedStandards:LSP4DigitalCertificate` > `0xabf0613c` ❌  
`SupportedStandards:LSP4DigitalAsset` > **`0xa4d96624`** ✅ 
+  all occurences of word ~_"Certificate"_~ by _**"Asset"**_

LSP4: fix old deprecated `SupportedStandards` key-value pair

---

LSPs/LSP-6-KeyManager.md

- fix return types in LSP6 from `returns (bool)` to `returns (bytes memory)`.
- changed order of method, putting `getNonce` first.

fix: return types for LSP6

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

Improvement and fixes for ERC725Y keys descriptions and JSON schemas (snippets).
Organised layout of each ERC725Y JSON schema across LSPs
- **improve readability** by putting `valueType` first, `valueContent` second
For other fixes, see commit titles below

refactor: improve ERC725Y keys descriptions

---

LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md

The ERC725Y keys `SupportedStandards:{StandardName}` are defined with `bytes` as their `valueType`
However, these keys all use a `bytes4` literal as a value `valueContent`
Change the LSP Metadata specs that use these key by specifying `bytes4`  as `valueType`

refactor: use `bytes4` for `SupportedStandards` key

---

LSPs/LSP-2-ERC725YJSONSchema.md

Improve readability, layout and structure of LSP2 - ERC725Y JSON Schema.
➡️  **For a preview, see here:** https://github.com/CJ42/LIPs/blob/refactor/lsp2/LSPs/LSP-2-ERC725YJSONSchema.md
- For `valueType`
- added `boolean` type
- added signed integers `intN`
- For `valueContent`
- added `Boolean`
- used keyword `Literal` for constant value content like `0x13456ABCD...`
Most of the content has been improved, by adding more precisions on specifications and requirements. 
- improved content for **Simple Summary**, **Abstract** and **Motivation**.
- added table with quick links at the top for `name`, `key`, `keyType`, `valueType` and `valueContent`.
- created sections for `name`, `key`, `keyType`, `valueType` and `valueContent`
- added tables with available types for `keyType`, `valueType` and …

refactor: improve LSP2 specs

---

LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md

For the following Map keys with a **Mixed** `valueContent`:
- `LSP3IssuedAssetsMap`
- `LSP4CreatorsMap`
- `LSP5ReceivedAssetsMap`
Add the following precision for second `bytes4` of the `valueContent`:
If the address is either an EOA, or a contract with an unknown interface ID, `standardInterfaceId = 0x00000000`

docs: add precision for unknown interface ID for "Mixed" map keys

---

LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-9-Vault.md

- Create the standards for LSP9 and LSP10:
- LSP9 Representing a blockchain digital vault based on ERC725 and LSP1-UniversalReceiver
- LSP10 Representing metadata keys to list all vaults a UniversalProfile own.
Note: Still Missing Motivation

docs: Add LSP9Vault and LSP10ReceivedVaults Standards

---

LSPs/LSP-6-KeyManager.md

docs: add explanations for partial keys in LSP6

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

To avoid broken links due to (potential) changes in the repo URL in the future, switch all the links from url to local markdown file reference.
This makes also the markdown file easier to read.

docs: use internal links to markdown files instead of urls

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Adding function overloading in the Interface Cheat Sheet of LSP0, LSP7, LSP8, LSP9.
- Updating InterfaceID of LSP0, LSP9.
- ERC725Account: `0x481e0fe8`
- LSP9Vault: `0x5e38b596 `

Update InterfaceId and Interface Cheat Sheet

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

All of the ERC725Y JSON Schema of the keys with a `Map` keyword at the end (or in other words that have `<address>`:
- are defined as `Mapping` ❌ 
- but should `Bytes20Mapping` ✅

fix: errors in JSON schemas of keys

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Replacing the word `key` with `data keys` when referring to ERC725Y Keys.
This change excludes the **keywords** of all **LSP2ERC725YJSON**, example below:
```json
{
"name": "LSP1UniversalReceiverDelegate",
"key": "0x0cfc51aec37c55a4d0b1a65c6255c4bf2fbdf6277f3cc0730c45b828b6db8b47",
"keyType": "Singleton",
"valueType": "address",
"valueContent": "Address"
}
```
This is useful to distinguish between the normal keys (public/private keys) and the standardized ERC725Y keys (data keys).

docs: replace keys by data keys

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-9-Vault.md

Edit `Executed` event definitions in LSP0, LSP6 and LSP9 to use only the first 4 bytes of the function selector and reflect changes in:
- https://github.com/ERC725Alliance/ERC725/pull/98
- https://github.com/lukso-network/lsp-smart-contracts/pull/143

docs(events): edit `Executed` event definition in LSP0, 6 and 9

---

LSPs/LSP-5-ReceivedAssets.md

There is an error in the description of `LSP5ReceivedAssetsMap`
The value for interface ID is shown as `0xce33f65c3` :x:, while it should be `0xe33f65c3 ` ✅

fix: LSP5 bytes4 for interface ID

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-9-Vault.md

Add Claim Ownership in LSP0 and LSP9

---

LSPs/LSP-6-KeyManager.md

- Change InterfaceID for LSP6 to `0xc403d48f `.
- Re-order `executeRelayCall(..)` params.
- Add chainId to the signed message.
NB: To not merge till lsp-smart-contract is released.

Edit `executeRelayCall(..)` function (chainId, params)

---

LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-12-IssuedAssets.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

this follow the changes introduced in https://github.com/lukso-network/LIPs/commit/2d2c727956ad1fe0bcbb496e6719a626925b116b

change `Bytes20Mapping` and `Bytes20MappingWithGrouping` keys schemas across LSPs

---

LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-6-KeyManager.md

- Fixing the `SupportedStandards:XYZ` Keys after the change in LSP2.
- TODO: Add `SupportedStandards:LSP9Vault` in LSP9

change `SupportedStandards` Keys

---

LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-12-IssuedAssets.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-3-UniversalProfile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md

Currently most Map data keys schemas define the valueContent as `Mixed`.
This does not provide context on how to decode and interpret the raw underlying bytes stored under such keys, as these could be of any types.
1. add description about the possibility of using tuple of types for:
- `valueType` = _e.g._ `(bytes4,bytes8)`
- `valueContent` = _e.g._ `(Bytes4,Number)`
2. change Map keys in LSP4, LSP5, LSP10 and LSP12 to use tuples for `valueType` and `valueContent`

Use tuple of instead of `Mixed` for LSP2 Map data keys

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-9-Vault.md

- Mark `universalReceiver` function as payable
- Add value param to the UniversalReceiver event
- Add value param to the `universalReceiverDelegate` function
- Change the `LSP1Delegate` InterfaceID

Improve LSP1-UniversalReceiver standard

---

LSPs/LSP-2-ERC725YJSONSchema.md

The text in the LSP2 standard is outdated LSP3issuedAssets should be replaced with LSP12, and the keys reference.

Change `LSP3IssuedAssets` to `LSP12IssuedAssets`

---

LSPs/LSP-9-Vault.md

The data key `SupportedStandards:LSP9Vault` is missing in the Implementation cheatsheet of LSP9

add SupportedStandard:LSP9 data key in LSP9 cheatsheet

---

LSPs/LSP-2-ERC725YJSONSchema.md

Line [62](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md?plain=1#L62) says there is `Boolean` but `Boolean` was missing from the main content table.
Either we delete from L62 or we add it as per this PR.

Add missing Boolean type on LSP-2

---

LSPs/LSP-2-ERC725YJSONSchema.md

- Fixed `<mixed type>` related sentences;
- Fixed a few places where the verb `its` should be replaced with `it's`;
- Updated wording under the `Data Key Name` section.

chore: LSP2 - minor suggestions, fixed typos

---

LSPs/LSP-7-DigitalAsset.md

Assuming that LSP7 is for tokens like ERC20, not NFT like LSP8 it might be confusing in sense that some might think that setting isNFT to true would create an NFT, which is not entirely true. In this sense the param should be rather called isNonDivisible.

Change NFT to non-divisible

---

LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-12-IssuedAssets.md
LSPs/LSP-5-ReceivedAssets.md

Fix mappings data keys errors

---

LSPs/LSP-7-DigitalAsset.md

Add warning about Allowance Double-Spend Exploit in LSP7.

[QSP-9] Add warning about Allowance Double-Spend Exploit in LSP7

---

LSPs/LSP-7-DigitalAsset.md

Mistake in the LSP7DigitalAsset docs. Input parameters for `isOperatorFor` is flipped around  (operator <-> tokenOwner )

Mistake in LSP-7-DigitalAsset doc

---

LSPs/LSP-12-IssuedAssets.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-7-DigitalAsset.md

- Change `isOperatorFor` in LSP7 to `authorizedAmountFor`
- Update the `interfaceId` of LSP7 `0xe33f65c3` -> `0x5fcaac27`
`isOperatorFor(address operator, address tokenOwner)` this method returns `uint256`, the amount of tokens that `operator` is authorised to spend on behalf of `tokenOwner`. The naming of the method is quite misleading as one would expect that `isOperatorFor` would return a `bool`. That’s why the name `authorizedAmountFor` would fit better in this context.

[QSP - Best Practices] Change isOperatorFor(..) to authorizedAmountFor(..) in LSP7

---

LSPs/LSP-6-KeyManager.md

Updated block of JS code where permissions' names and values are declared, with related documentation.
Moved JS docs for permissions to be on top of each permission constant, not on the same line as the constant as these docs were almost invisible.
Other related topics to discuss are:
1) the naming of `SUPER_...` permissions;
Suggest removing `SUPER_` prefix from permissions that have no limitations and adding prefix to permissions that **represent a subset** of current `SUPER_` permissions. 
2) Image with an example of permissions - looks like Alice doesn't have SUPER permissions and the total value of assigned permissions `0x...ffff` shown on the right side of the image is incorrect? In [`lsp-smart-contracts`](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/constants.js …

chore: updated permissions declaration/description format

---

LSPs/LSP-7-DigitalAsset.md

- Use `uint8` instead of `uint256` in LSP7 decimals
We don't need `uint256` for decimals, `uint8` is more than enough. With `uint8`, decimals can be used up to 255.
Most implementations use 18 as a decimal number.

Use `uint8` instead of `uint256` decimals in LSP7

---

LSPs/LSP-6-KeyManager.md

Introduce a new permission `ENCRYPT` in the LSP6 standard, placed after SIGN and before the SUPER permissions.

feat!: add ENCRYPT permission in LSP6

---

LSPs/LSP-9-Vault.md

- DELEGATECALL is a dangerous operation, it can lead to changing the storage variables and destroying the contract itself, that's why it should be an optional operation and the decision to implement should go to each developer.

Mark DELEGATECALL as optional operation in LSP9

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Marking the value field as indexed
- Remove the indexed from the returnedValue
- Switch between receivedData and returnedValue parameters.
- Add dataValue param to LSP0 - LSP7 - LSP8 - LSP9
Before: 
```js
event UniversalReceiver(
address indexed from,
uint256 value,
bytes32 indexed typeId,
bytes indexed returnedValue,
bytes receivedData,
);
```
Now: 
```js
event UniversalReceiver(
address indexed from,
uint256 indexed value,
bytes32 indexed typeId,
bytes receivedData,
bytes returnedValue
);
```
Note: Event signature will not change since both switched parameters are bytes.

Switch the returnedValue with the receivedData values in UniversalReceiver Event

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-14-Ownable2Step.md
LSPs/LSP-9-Vault.md

This PR introduces LSP14Ownable2Step, an LSP focused towards the following processes:
- owning a contract
- transferring ownership of a contract
- renouncing ownership of a contract
Introduced features:
- Transfer ownership in 2 steps.
- Renounce ownership in 2 steps.
- Notify the new owner whenever the first step of transfer ownership is executed.
- Notify both the old owner and the new owner whenever the process of transferring ownership is complete.

Create LSP14Ownable2Step specs 

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Move the LSP1 Hooks section to the transfer function
- Update the typeId from:
- keccak256('LSP7TokensSender') --> keccak256('LSP7Tokens_SenderNotification')
- keccak256('LSP7TokensRecipient') --> keccak256('LSP7Tokens_RecipientNotification')
- keccak256('LSP8TokensSender') --> keccak256('LSP8Tokens_SenderNotification')
- keccak256('LSP8TokensRecipient') --> keccak256('LSP8Tokens_RecipientNotification')

Re-organize hooks section and update typeId in tokens standards

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

Improve the description section for **LSP8TokenIdType**, using a table to clarify how to treat and deal with each different type of `tokenId`.
This is to avoid confusion for the type `3` (`bytes32`).
Related to:
- https://github.com/lukso-network/LIPs/pull/143
- https://github.com/lukso-network/LIPs/issues/136

improve explanation for section `LSP8TokenIdType` + add tokenId type `4` for `string`

---

LSPs/LSP-2-ERC725YJSONSchema.md

- improve the generic description of `valueContent` in LSP2, including a basic example of displaying information in a user interface.
- add extra note about `valueContent` in the case of arrays.

LSP2: (related to [WP-D24]) Improve description of `valueContent` for the case of arrays

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

There was an incomplete duplication of **tokenId** types explanation. Looks like it's just something that was left from the older version of the LSP8 standard.

chore: removed duplication of tokenId type explanations

---

LSPs/LSP-2-ERC725YJSONSchema.md

The table under Specifications was missing [`bytes[CompactBytesArray]`](#bytescompactbytesarray) and `bytesN[CompactBytesArray]`.

fix: added references to new value types in the table

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-17-ContractExtension.md
LSPs/LSP-9-Vault.md

- Simplify the LSP17ContractExtension by not enforcing any behavior of storing selectors to addresses, events, talking about ERC725Y , etc ..
- Update different sections, Rational, Motivation, Abstract.
- Add the modification requirements in LSP0 and LSP9

Simplify LSP17ContractExtension Standard

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-14-Ownable2Step.md
LSPs/LSP-9-Vault.md

In this PR the following changes are introduced:
- Adding a note in LSP14 about the possibility of overriding the Type IDs of the hooks called by `transferOwnership(..)` and `acceptOwnership(..)`
- Adding requirements in LSP0 and LSP9 about overriding the Type IDs in LSP14

Document LSP14 Type IDs overriding

---

LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-6-KeyManager.md

After some internal discussions, we decided that limiting the maximum element size to 255 was not enough and updated the length element size to a `bytes2` value (initially byte1)

feat: change element length size to bytes2

---

LSPs/LSP-2-ERC725YJSONSchema.md

- Improve section about Tuple of `valueType`s with examples.
- Add Table of Content at the top for LSP2.

LSP2: improve section for tuples of `valueType` + add Table of Content at the top.

---

LSPs/LSP-2-ERC725YJSONSchema.md

- A few tuple links were broken;
- Added link to bytesN[CompactBytesArray] in one of the tables.

fix: links in LSP2

---

LSPs/LSP-2-ERC725YJSONSchema.md

# What does this PR introduce?
in LSP2, when a data key is of keyType `Array`, change the type of the value stored (for the total number of elements in the Array) 
- **before**: `uint256` ❌ 
- **now**: `uint128` ✅ 
The reason for this change is to not store conflicting information under a metadata key of keyType Array. Since the index part are 16 bytes long, the max possible index (= the max number of elements that can be stored) is the max `uint128` value.
This would also prevent mistakes when casting is done to write or update Array data keys in implementation contracts,

LSP2!: change value stored under an Array length data key as `uint128`

---

LSPs/LSP-0-ERC725Account.md

Update Fallback behavior for graffiti extension:
- Do not revert when there is not extension set for `bytes4(0)`

Update Fallback Behavior in LSP0

---

LSPs/LSP-9-Vault.md

Update Fallback behavior for graffiti extension:
- Do not revert when there is not extension set for `bytes4(0)`

Update Fallback Behavior in LSP9

---

LSPs/LSP-9-Vault.md

There was no link previously, only [lsp-universalprofile-smart-contracts] text. Also by example from LSP3 added a block with the whole JSON interface.
Here is what LSP3 looks like:

fix: LSP9Vault link + JSON interface as one piece

---

LSPs/LSP-6-KeyManager.md

It looks like an old link was used and clicking on it didn't lead the reader to the Permissions section.

fix: LSP6 permissions section link

---

LSPs/LSP-7-DigitalAsset.md

In the LSP-7 cheat sheet, the ERC173 is used amongst other standards, but it's not mentioned as a requirement in the `requires` column in the header.

chore: added ERC173 to requirements of LSP-7

---

LSPs/LSP-6-KeyManager.md

- Adding the new behavior of AllowedCalls where an additional bytes4 representing a bitArray was added to the AllowedCall dataKey.
A bitArray that represents the list of operations that the restrictions listed applies for.
The operations are defined with specific bits, starting from the 4th byte from the most right: 
- transferValue `00000001`
- call `00000010`
- staticcall `00000100`
- delegatecall `00001000`

Update LSP6 Specs with new behavior of AllowedCalls

---

LSPs/LSP-6-KeyManager.md

The cheat sheet of LSP6 was outdated.

fix: bring LSP6 cheat sheet up to date

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

It might be relevant having the ability to have a baseURI key in the ERC725Y key/value store of a LS8 contract.
Indeed, for now, if you want to link metadata to your tokenIds, you'll need to use the mapping key LSP8TokenIdMetadata:TokenId, which means having one key per tokenId. Imagine a collection with thousands of tokens as we know, it would be quite expensive.
Instead, it would be relevant using an already existing system, which is the baseURI.
This PR could be followed by another PR in the LSP8CompatibleERC721.sol smart contract, updating the tokenURI method.

feat: LSP8MetadataBaseURI ERC725Y JSONSchema key

---

LSPs/LSP-4-DigitalAsset-Metadata.md

Following the idea from the existing [OpenSea metadataStandard](https://docs.opensea.io/docs/metadata-standards#attributes), it would be interesting adding an area to have custom metadata related to assets. 
I kept the "attributes" wording (not sure about it though) naming but changed the "trait_type" for "key", for two reasons:
- Using Lukso, you're used to the term "key"
- It's not necessarily a trait, it's just some custom metadata

feat: LSP4 Metadata with custom attributes

---

LSPs/LSP-4-DigitalAsset-Metadata.md

- add the `"attributes"` array field in the JSON under the `LSP4Metadata`
- for the `LSP4TokenName` and `LSP4TokenSymbol`:
- mark these data keys as optional
- add sections for requirements + recommendations if these data key are used

[LSP4] Mark `LSP4TokenName` + `LSP4TokenSymbol` as OPTIONAL + add requirements if used

---

LSPs/LSP-0-ERC725Account.md

Fix the specs for LSP0 for the function `transferOwnership(address)` and `renounceOwnership()`.
These functions are marked as `payable` but they shouldn't.

[TRST-L1] mark ownership transfer/renounce functions as non-payable in LSP0

---

LSPs/LSP-1-UniversalReceiver.md

Add a note in section in the LSP1 standard for the `universalReceiver(...)` function to specify that:
- it is possible for the function to return no data as `0x`
- if any `bytes` data is returned, it MUST be abi-encoded according to the ABI specs.

[TRST-M4] add notes about allowing the `universalReceiver(...)` function to return no data (void return)

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-20-CallVerification.md
LSPs/LSP-9-Vault.md

- Improve the specs for LSP0 and LSP9 `universalReceiver(...)` function to describe that execution continues normally if the address stored under the data keys `LSP1UniversalReceiverDelegate` and `LSP1UniversalReceiverDelegate:<bytes32>` do not support the LSP1 interface ID.
- group the content for both LSP1 data keys in one big section paragraph.
- add _Requirements_ as subheaders for each methods.
- explicitly state that if the function being called does not return anything, the `callResult` value MUST be an empty `bytes`
Improve specs.
- add brief description under each method `lsp20VerifyCall(...)` and `lsp20VerifyCallResult(...)`

[TRST-R3] Specification improvements for LSP0 and LSP20

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-20-CallVerification.md

- [Specify how the result for lsp20VerifyCallResult is encoded in LSP0](https://github.com/lukso-network/LIPs/commit/aa9a48dea99a083e841e92cd5ce7b3b05d293d00)
- [Explain the use of callHash in lsp20VerifyCallResult in LSP20](https://github.com/lukso-network/LIPs/commit/eb3476f297afc9d3b939e560145d0477b0f090eb)

Add LSP20 documentation about `callHash`and result encoding

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Remove the function overloading
- Update `setData` to `setDataBatch` , `getData` to `getDataBatch` , `execute` to `executeBatch`, `executeRelayCall` to `executeRelayCallBatch`
- Update interfaceIds

Remove function overloading for ERC725 and LSP6

---

LSPs/LSP-0-ERC725Account.md

Add LSP20 in calculation of LSP0 interface ID.
The interface ID of LSP0 is changing from `0x3e89ad98` to -> `0x24871b3d`

chore!: add LSP20 standard in calculation of LSP0 interface ID

---

LSPs/LSP-6-KeyManager.md

Change event name from `VerifiedCalled` to `PermissionsVerified` in LSP6 specs.

refactor!: [LSP6] change event name from `VerifiedCalled` to `PermissionsVerified` in LSP6

---

LSPs/LSP-15-TransactionRelayServiceAPI.md

Add validityTimestamps to Relayer API spec. 
If no validity timestamps value is passed the relayer should assume it is 0

Update LSP15 to include validityTimestamps

---

.prettierignore
.prettierrc
LSPs/LSP-8-IdentifiableDigitalAsset.md

- add prettier to prettify Markdown files of specs.
- change the order of the tokenId type to the following table below. TokenId type now starts at `0`.
- change the ERC725Y data key from `LSP8ReferenceFrom` to `LSP8ReferenceContract` + improve description in specs.

LSP8 changes for tokenId type and `LSP8ReferenceContract` data key + Add Prettier configs

---

LSPs/LSP-17-ContractExtension.md

- Add subheader section under LSP17 Extendable specifications.
- Add note about the fact that `msg.value` is not forwarded to the extension contract (Related to Code4Rena QA #141, L-02)

update section of LSP17 specs + add note about `msg.value` not forwarded to extension

---

LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

-  fix typo in LSP4 specs (the LSP4 MD file got prettified automatically)
- update old ERC725Y schema for LSP8 at the bottom of the specs

Update old schemas at the bottom of LSP8 specs

---

LSPs/LSP-25-ExecuteRelayCall.md
LSPs/LSP-6-KeyManager.md

- Change interface Id of LSP6 from `0x38bb3cdb` to `0x627ca5d3`
Closes #221

create LSP25 Execute Relay Call standard, extracting functions from LSP6 standard

---

LSPs/LSP-20-CallVerification.md

Add callee param to lsp20

---

LSPs/LSP-3-Profile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md

To allow for more flexible ways to very images and other sources referenced from smart contracts, we should change the property names in LSP3 and LSP4 for images and asset content to `verificationFunction`, `verificationData `
```js
{ // example of a verificationData based image verification
"width": Number,
"height": Number,
"verificationFunction": 'keccak256(bytes)',
"verificationData": 'string', // bytes32 hash of the image
"url": 'string'
},
{ // example of a signature based image verification
"width": Number,
"height": Number,
"verificationFunction": 'ecdsa',
"verificationData": 'string', // signer that signed the bytes of the image
"verificationSource": 'string' // e.g url returning the signature of the signed image
"url": 'string'
},
```
This way it can also be used to verify …

LSP3/4: change hash to verification data

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Mark `increaseAllowance` and `decreaseAllowance` as part of the interface resulting in a change of interfaceId in LSP7
- Add boolean parameter to revokeOperator to signal whether to notify or not in LSP7 and LSP8 resulting in interfaceId change.
- Mark the notification in increase/decreaseAllowance and authorizeOperator as mandatory that does revert when the receiver revert. These notifications only occurs in case the operator supports LSP1.
Add missing changes such as parameters in events, etc ..

Update LSP7 and LSP8 InterfaceId and function signature (Notification Changes)

---

LSPs/LSP-3-Profile-Metadata.md
LSPs/LSP-4-DigitalAsset-Metadata.md

After discussing the properties, we found that it is better to put the verification into a new object, so its more upgradable in the future.
e.g.
```js
load for better loading performance
"profileImage": [ // One image in different sizes, representing the profile.
{ // example of a hash based image verification
"width": Number,
"height": Number,
"url": 'string',
"verification": {
"method": 'keccak256(bytes)',
"data": 'string', // bytes32 hash of the image
}
},
{ // example of a signature based image verification
"width": Number,
"height": Number,
"url": 'string',
"verification": {
"method": 'ecdsa',
"data": 'string', // signer that signed the bytes of the image
"source": 'string' // e.g url returning the signature of the signed image
}
},
{ // example of a NFT/smart contract based image …
```

LSP3,4: changed to verification object

---

LSPs/LSP-3-Profile-Metadata.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

Updated LSP3 to use VerifiableURI instead of JSONURL.
It doesn't seem that we need to change anything else since those schemas have `keyType` Singleton. `key` value stays the same.

fix: changing JSONURL uses to VerifiableURI in LSP-3-Profile-Metadata.md

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Add missing arrays for bool parameter in `transferBatch(..)` in LSP7 and LSP8

[M-01] transferBatch() is declared wrongly in the LSP7 and LSP8 specification

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Add the caller to the LSP1 transfer hooks
- Replace packed encoded with ABI-encoded

[M-02] LSP1 hooks for transfer() are declared wrongly in the LSP-7 specification

---

LSPs/LSP-7-DigitalAsset.md

- Remove recommendation of revokeOperator then authorizeOperator
- Advise use of increase/decrease Allowance in LSP7

[L-06] revokeOperator() does not protect against the double-spending allowance attack

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

- Add *Requirements*:
- `operator` cannot be authorized for `tokenId`.
- Add `notify` parameter description.
- Add *Requirements*:
- `operator` cannot be already authorized for the same tokenId.
- Remove the inaccurate *Requirements* below:
- caller must be current `tokenOwner` of `tokenId`.
- Remove the inaccurate *Requirements* below:
- caller must be current `tokenOwner` of `tokenId`.
- `operator` cannot be calling address.
- Remove from *Parameters* section and include in *Requirements* section
- `from` and `to` cannot be the same address.
- Add *Requirements*:
- `from`, `to`, `amount`, `force`, and `data`  lists are the same length.
- `transferBatch()` - `force` parameter: `bool` array ---> `bool[] memory force`.
- `batchCalls()` - `data`: `calldata`. ---> `memory`
- …

[I-05] Inconsistencies in the LSP-8 specification

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

Explain how the value should be set/get for `LSP8TokenIdFormat` for the specific tokenId to avoid wrong format.

Add more details for `LSP8TokenIdFormat` in LSP8 specs

---

LSPs/LSP-4-DigitalAsset-Metadata.md

`tokenId` is used in LSP8 not LSP7, that's why comment is misleading.

fix: update comment in example LSP4 object

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- allow self transfer
- allow operator to revoke himself
- update the interfaceId to latest specs

Allow operator to revoke himself + Self Transfers in Token Standards

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-11-BasicSocialRecovery.md
LSPs/LSP-16-UniversalFactory.md
LSPs/LSP-17-ContractExtension.md
LSPs/LSP-20-CallVerification.md
LSPs/LSP-23-LinkedContractsFactory.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-9-Vault.md

Noticed that old links to smart contract implementation were no longer working.

fix: outdated links for lsp-smart-contracts replaced with new ones

---

.github/workflows/spellcheck.yaml
LSPs/LSP-28-TheGrid.md

- fix the main object structure (array instead of object)
- add missing grid `visibility` field
- update X widget (no more timeline support)
- add example of `QR_CODE` widget
- improve comments / document structure
Additionally fix spell check job due to deprecated version of `actions/upload-artifact: v3`

fix: Fix issues in LSP28 Grid JSON schema
