lukso-network/LIPs

LSPs/LSP-3-UniversalProfile.md
LSPs/LSP-4-DigitalCertificate.md

Includes interface cheat sheet + flow charts

LSP6 Key Manager

---

LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-3-UniversalProfile.md
LSPs/LSP-4-DigitalCertificate.md
LSPs/LSP-6-KeyManager.md

- Changed external to public 
- Added some references
- Edited the "requires" section
- Added Specification for UniversalRecieverDelegate
- Edited the Interface Cheat Sheet for LSP4 
- Changed setData + getData functions

Editing LSPs (Interface Cheat Sheet, etc ..)

---

LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-3-UniversalProfile.md
LSPs/LSP-6-KeyManager.md

- Added doc to the nonce
- Edited `getNonce` function
- Changed `public` to `external` in the Interface Cheat Sheet
- Order of the keyMananager signed message

Documentation For the Nonce

---

LSPs/LSP-2-ERC725YJSONSchema.md

Add LSP-2 AssetURL example

---

LSPs/LSP-6-KeyManager.md

Add missing `AddressPermissions[]` in Implementation section

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

docs: change LSP8 Implementation deprecated link

---

LSPs/LSP-6-KeyManager.md

add specification + bytes12 Mapping key for `AddressPermissions:AllowedERC725YKeys:AllowedERC725YKeys`

feat: `AddressPermissions:AllowedERC725YKeys`

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Remove `dataValue` parameter from **[DataChanged](https://github.com/ERC725Alliance/ERC725/blob/develop/docs/ERC-725.md#datachanged)** event.

change `DataChanged` event in Cheat Sheet

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md
LSPs/LSP-9-Vault.md

- Cleaning Interface Cheat Sheets
- Removing typos and false information
- Improving some sentences
- Improving Examples in LSP1 Standard

improve standards and examples

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-9-Vault.md

- Add fallback function the cheat sheet

Add `fallback(..)` function to Cheat Sheet

---

LSPs/LSP-9-Vault.md

- Add `SupportedStandards:LSP9Vault` data key

Add `SupportedStandards:LSP9Vault` data key

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
LSPs/LSP-9-Vault.md

- Adding hooks section to LSP7 - LSP8 - LSP9 Specification
TBD: Data sent in the vault hook

Add Hooks section to LSP7/8/9 Specification

---

LSPs/LSP-8-IdentifiableDigitalAsset.md

add additional requirement found from issue below in LSP8 specs: 
https://github.com/lukso-network/lsp-smart-contracts/pull/266

[QSP-3] add extra requirement for transfer functions in LSP8

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-9-Vault.md

This PR updated the LIPs according to the latest updates in the smart contracts around `transferOwnership` and `renounceOwnerhsip`.

[LSP0 and LSP9] document 2 steps process for `renounceOwnership` + add requirement in `transferOwnership`

---

LSPs/LSP-0-ERC725Account.md

- Updating the LSP0 Specification to describe the behavior wanted for every LSP0 compliant contract.
> Just review the specification section, not the other sections :)

Update LSP0 to include more specifications

---

LSPs/LSP-9-Vault.md

- Updating the LSP9 Specification to describe the behavior wanted for every LSP9 compliant contract.
> Just review the specification section, not the other sections :)

Update LSP9 to include more specifications

---

LSPs/LSP-15-TransactionRelayServiceAPI.md

Added improvements to LSP15-TransactionRelayServiceAPI specification

Improvements for TransactionRelayServiceAPI

---

LSPs/LSP-17-ContractExtension.md

- First draft of LSP17ContractExtension

Add first draft of LSP17ContractExtension

---

LSPs/LSP-16-UniversalFactory.md

- Adds the first draft of LSP16

Add first draft of LSP16UniversalFactory

---

LSPs/LSP-11-BasicSocialRecovery.md
LSPs/LSP-11-SocialRecovery.md

- Introducing **LSP11BasicSocialRecovery** standard specs

docs: add first draft of LSP11 specs

---

LSPs/LSP-11-BasicSocialRecovery.md
LSPs/LSP-6-KeyManager.md

The permission `ADDPERMISSIONS` is now `ADDCONTROLLER`.

Change `ADDPERMISSIONS` to `ADDCONTROLLER`

---

LSPs/LSP-2-ERC725YJSONSchema.md

For reference, see ➡️  https://github.com/ERC725Alliance/erc725.js/pull/266#issuecomment-1411250135

LSP2: change `boolean` -> `bool`

---

LSPs/LSP-11-BasicSocialRecovery.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-6-KeyManager.md

Changing the name of the `CHANGEPERMISSIONS` permission to `EDITPERMISSIONS`.

Change `CHANGEPERMISSIONS` to `EDITPERMISSIONS`

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-9-Vault.md

- Adding batchCalls function to LSP0 and LSP9
- Change the interfaceId accordingly

Add batchCalls function to LSP0 and LSP9

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-6-KeyManager.md

Update LSP0 and LSP6 to new behavior

---

LSPs/LSP-20-CallVerification.md

Add an extra section on handling the case of the verification failure for the LSP20 standard.

[WP-D7] LSP20: The standard should provide a clearer guide for handling verification failures.

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-9-Vault.md

- Add Graffiti section in LSP0 and LSP9

[WP-D10] Add Graffiti section in LSP0 and LSP9

---

LSPs/LSP-16-UniversalFactory.md

- Finalize LSP16 Specification

Update LSP16 Specification

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-17-ContractExtension.md
LSPs/LSP-9-Vault.md

Mention these data keys as examples that COULD be used.

add LSP1 + LSP17 data keys schemas under their respective standards

---

LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

- Correct LSP7 and LSP8 InterfaceId

[C4#122] Correct LSP7 and LSP8 InterfaceId

---

LSPs/LSP-10-ReceivedVaults.md
LSPs/LSP-12-IssuedAssets.md
LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-5-ReceivedAssets.md

Also changed references in the text for the other Map values from `bytes8` to `uint128`.

Fix incorrect value in `LSP4CreatorsMap` tuple from `bytes8` to `uint128`

---

LSPs/LSP-23-LinkedContractsFactory.md

create LSP23 LinkedContractsFactory

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-20-CallVerification.md
LSPs/LSP-6-KeyManager.md

- Remove magic value occurrence 
- Replace with `returnedStatus` and `success value`

Remove magic value occurrence 

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-9-Vault.md

- Add `universalReceiverDelegate` function in LSP1Delegate

Add universalReceiverDelegate function in LSP1Delegate

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-14-Ownable2Step.md
LSPs/LSP-17-ContractExtension.md

Improve LSP0 and LSP14 and LSP17 Specification 
- Adding lsp1 data to the lsp14 functions
- Updating optional schema to LSP17
- Improve LSP0 specification

Improve LSP0 and LSP14 and LSP17 Specification 

---

LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-8-IdentifiableDigitalAsset.md

fix: adjust details about padding / cutting rules + add summary table in LSP2 + LSP8

---

LSPs/LSP-4-DigitalAsset-Metadata.md
LSPs/LSP-7-DigitalAsset.md
LSPs/LSP-8-IdentifiableDigitalAsset.md
README.md

- Move back LSP4 to "Draft"
- Change status for LSP7 + LSP8 from "Last Call" to "Review"

add "Review" in LIP status + change LSP4/7/8 status

---

LSPs/LSP-16-UniversalFactory.md

- Update LSP16 configs 
- Move specs to Review

Update LSP16 configs and move specs to Review

---

LSPs/LSP-17-ContractExtension.md

- Improve LSP17-ContractExtension explanation 
- Move to Review

Improve LSP17-ContractExtension explanation and move to Review

---

LSPs/LSP-4-DigitalAsset-Metadata.md

Add more detailed comments about assets in LSP4.

doc: Update assets comments for LSP4

---

LSPs/LSP-7-DigitalAsset.md

Put sender/recipient in bold to improve readability.
Initial issue:
https://github.com/lukso-network/docs/issues/845

Improve readability: Add sender/recipient in bold for LSP7

---

LSPs/LSP-20-CallVerification.md

- Improve LSP20 explanation
- add a diagram

Improve LSP20 explanation

---

LSPs/LSP-2-ERC725YJSONSchema.md

Adjusted indents in one of the LSP2's examples.

chore: spacing fix in LSP-2-ERC725YJSONSchema.md

---

LSPs/LSP-0-ERC725Account.md
LSPs/LSP-1-UniversalReceiver.md
LSPs/LSP-11-BasicSocialRecovery.md
LSPs/LSP-14-Ownable2Step.md
LSPs/LSP-15-TransactionRelayServiceAPI.md
LSPs/LSP-16-UniversalFactory.md
LSPs/LSP-17-ContractExtension.md
LSPs/LSP-2-ERC725YJSONSchema.md
LSPs/LSP-20-CallVerification.md
LSPs/LSP-23-LinkedContractsFactory.md
LSPs/LSP-25-ExecuteRelayCall.md
LSPs/LSP-5-ReceivedAssets.md
LSPs/LSP-6-KeyManager.md

Based on the Word document summary provided by @frozeman

chore: add quick abstract paragraphs for accounts and generic standards

---

LSPs/LSP-1-UniversalReceiver.md

add order of execution for LSP1 delegates
first default one, then custom

Add order of execution for LSP1 URD
